name: go-test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/go-test.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/workflows/go-setup
      - name: go vet
        run: go vet ./...
      - name: go test
        run: go test -race -cpu=1,2,4 ./...
